config/routes.rb
Rails.application.routes.draw do
  root to: 'ideas#index'
  devise_for :users
  resources :ideas do
    resources :comments
    resource :likes, controller: 'ideas/likes'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
end

app/models/idea.rb
class Idea < ApplicationRecord
  has_many :comments
  has_many :idea_likes, :dependent => :destroy
end

app/models/idea_like.rb
class IdeaLike < ApplicationRecord
  belongs_to :idea
  belongs_to :user

  validates :idea_id, uniqueness: {scope: :user_id, message: "has been a ready liked!"}
end

app/models/user.rb
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable, :rememberable, :trackable
  devise :database_authenticatable, :registerable, :validatable

  has_many :ideas
  has_many :idea_likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @idea = Idea.find(params[:idea_id])
    @comments = @idea.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @idea = Idea.find(params[:idea_id])
    @comments = @idea.comments.find(params[:id])
  end

  # GET /comments/new
  def new
    @idea = Idea.find(params[:idea_id])
    @comment = @idea.comments.build
  end

  # GET /comments/1/edit
  def edit
    @idea = Idea.find(params[:idea_id])
    @comment = @idea.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @idea = Idea.find(params[:idea_id])
    @comment = @idea.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html {redirect_to request.referer, notice: 'Comment was successfully created.'}
        format.json {render :show, status: :created, location: @comment}
      else
        format.html {render :new}
        format.json {render json: @comment.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html {redirect_to @comment.idea, notice: 'Comment was successfully updated.'}
        format.json {render :show, status: :ok, location: @comment}
      else
        format.html {render :edit}
        format.json {render json: @comment.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @idea = Idea.find(params[:idea_id])
    @comment.destroy

    respond_to do |format|
      format.html {redirect_to idea_comments_url, notice: 'Comment was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:user_name, :body, :idea_id)
  end
end

app/controllers/ideas/likes_controller.rb
module Ideas
  class LikesController < ApplicationController

    def show
      @idea = Idea.find(params[:idea_id])
      @idea_like = @idea.idea_likes.all
    end

    def create
      @idea = Idea.find(params[:idea_id])
      @idea_like = @idea.idea_likes.build(user: current_user)

      respond_to do |format|
        if @idea_like.save
          format.html {redirect_to @idea, notice: 'Idea was successfully liked.'}
          format.json {render :show, status: :created, location: @idea_like}
        else
          format.html {redirect_to @idea, alert: @idea_like.errors.full_messages.join('\n')}
          format.json {render json: @idea_like.errors, status: :unprocessable_entity}
        end
      end
    end

    def destroy
      @idea = Idea.find(params[:idea_id])
      @idea.idea_likes.where(user: current_user).destroy_all

      respond_to do |format|
        format.html {redirect_to @idea, notice: 'Idea was successfully unliked.'}
        format.json {head :no_content}
      end
    end


  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, exept: [:index, :show]
  before_action :set_idea, only: [:edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound do |e|
    redirect_to ideas_path, alert: 'There is no such idea or you have no permissions to do that'
  end

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])
    @comments = @idea.comments.all
    @comment = @idea.comments.build
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.build(idea_params)

    respond_to do |format|
      if @idea.save
        format.html {redirect_to @idea, notice: 'Idea was successfully created.'}
        format.json {render :show, status: :created, location: @idea}
      else
        format.html {render :new}
        format.json {render json: @idea.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html {redirect_to @idea, notice: 'Idea was successfully updated.'}
        format.json {render :show, status: :ok, location: @idea}
      else
        format.html {render :edit}
        format.json {render json: @idea.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy

    respond_to do |format|
      format.html {redirect_to ideas_url, notice: 'Idea was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_idea
    @idea = current_user.ideas.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def idea_params
    params.require(:idea).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/idea_likes_helper.rb
module IdeaLikesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/comments/_form.html.erb
<%= form_for([@comment.idea, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', idea_path %> |
<%= link_to 'Back', idea_comment_path(@idea) %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>User name</th>
    <th>Body</th>
    <th>Idea</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.body %></td>

      <td><%= link_to 'Show', [comment.idea, comment] %></td>
      <td><%= link_to 'Edit', edit_idea_comment_path(comment.idea, comment) %></td>
      <td><%= link_to 'Destroy', [comment.idea, comment], method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'comments/form', comment: @comment %>

app/views/comments/show.html.erb
<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @comment.idea_id %>
</p>

<%= link_to 'Edit', edit_idea_comment_path(@comment) %> |
<%= link_to 'Back', idea_path(@idea) %>

app/views/idea_likes/create.html.erb
<h1>IdeaLikes#create</h1>
<p>Find me in app/views/idea_likes/create.html.erb</p>

app/views/idea_likes/destroy.html.erb
<h1>IdeaLikes#destroy</h1>
<p>Find me in app/views/idea_likes/destroy.html.erb</p>

app/views/ideas/_form.html.erb
<%= form_with(model: @idea, local: true) do |form| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% @idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Ideas</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Likes</th>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @ideas.each do |idea| %>
    <tr>
      <td><%= idea.idea_likes.count %></td>
      <td><%= idea.title %></td>
      <td><%= idea.description %></td>
      <td><%= link_to 'Show', idea %></td>
      <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
      <td><%= link_to 'Destroy', idea, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>
<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>
<br>
<br>

<% if @idea.idea_likes.where(user: current_user).exists? %>
<% else %>
  <%= link_to 'Like', idea_likes_path(@idea), method: :post %>
<% end %>

<% if @idea.idea_likes.where(user: current_user).none? %>
<% else %>
  <%= link_to 'Unlike', idea_likes_path(@idea), method: :delete %>
<% end %>
<%= @idea.idea_likes.count %>
<br>
<br>

<%= render template: "comments/index" %>
<%= render template: "comments/new" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideas1</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Ideas', ideas_path %>
    Welcome |
    <% if current_user %>
      <%= current_user.email %>
      <%= link_to 'Logout', destroy_user_session_path %>
    <% else %>
      Guest
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Signup', new_user_registration_path %>
    <% end %>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
  <%= yield %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>
</body>
</html>